name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          # Download the .deb file
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"
          
          # Extract the contents of the .deb file
          dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/app

          # Create the IPA Payload directory
          mkdir -p ${{ github.workspace }}/ipa/Payload

          # Copy files from possible app locations
          if [ -d "${{ github.workspace }}/app/Applications" ]; then
            cp -R ${{ github.workspace }}/app/Applications/* ${{ github.workspace }}/ipa/Payload
          elif [ -d "${{ github.workspace }}/app/Library/MobileSubstrate/DynamicLibraries" ]; then
            # Assuming the app might be here; adjust as necessary based on the structure
            cp -R ${{ github.workspace }}/app/Library/MobileSubstrate/DynamicLibraries/* ${{ github.workspace }}/ipa/Payload
          else
            echo "No application files found in expected directories."
            exit 1
          fi
          
          # Create the IPA file
          cd ${{ github.workspace }}/ipa
          zip -r ${{ github.workspace }}/App.ipa .

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: ${{ github.workspace }}/ipa/App.ipa
